"""
Apply supervisor feedback to AgriXplain journal and conference Word papers.

Fixes:
- Research Gaps and Research Questions subsections in Introduction
- Dedicated Dataset Description section
- Methodology flowchart diagram in Section III
- Sequential figure numbering (Fig. 1, 2, 3, ...)
- Table captions (TABLE N.) above every table, sequential numbering
- Equation variables in italics
- Citations sorted in ascending order within brackets [1], [2], [3]
- Larger, readable regenerated figures where available
"""
from __future__ import annotations

import copy
import re
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches, Pt
from docx.text.paragraph import Paragraph

PAPER_DIR = Path(__file__).resolve().parent
FIG_DIR = PAPER_DIR / "figures"

RESEARCH_GAPS = (
    "C. Research Gaps\n"
    "A structured synthesis of the literature (Section II) reveals four persistent gaps that motivate "
    "this work. (G1) Reproducibility gap: no reviewed open platform publishes hardware pin maps, "
    "firmware symbols, training scripts, and REST contracts in a single auditable repository. "
    "(G2) Explainability gap: commercial bundles return yield labels without per-reading feature "
    "attribution suitable for agronomist review. (G3) Multimodal integration gap: vision, soil NPK, "
    "and environmental telemetry are rarely fused in one self-hostable stack. (G4) Benchmark gap: "
    "field trials are costly; reproducible synthetic benchmarks with documented generation rules "
    "are needed for fair algorithm comparison before deployment."
)

RESEARCH_QUESTIONS = (
    "D. Research Questions\n"
    "This study addresses the following research questions. RQ1: Can a commodity ESP32 edge station "
    "with documented calibration constants deliver reliable nine-dimensional feature vectors for "
    "yield-risk classification? RQ2: Does weighted probability fusion (AgriFusion) with "
    "disagreement-aware confidence damping outperform individual tree learners on a stratified "
    "hold-out benchmark? RQ3: Can TreeSHAP explanations be computed at inference time without "
    "violating sub-second API latency on a single-core server? RQ4: What deployment checklist and "
    "dataset documentation are required for regulatory and cooperative adoption of open smart-farming "
    "platforms?"
)

DATASET_INTRO = (
    "E. Benchmark Dataset Summary\n"
    "The platform benchmark uses N=2,200 reproducible synthetic samples (seven crops, nine features, "
    "three yield-risk classes) generated by backend/train_all_models.py with random_state=42. "
    "Section VII-A provides full generation rules, class distribution, and train–test protocol."
)

DATASET_ML_EXPAND = (
    "Table VIII-A summarizes feature ranges and class priors for the synthetic benchmark. "
    "The dataset is exported as training_data.csv in the repository root."
)

FIGURE_REPLACEMENTS = {
    "feature vector": "fig_feature_vector.png",
    "model performance comparison": "fig_model_comparison.png",
    "confusion matric": "fig_confusion_matrices.png",
    "weighted probability fusion algorithm": "fig_agrifusion.png",
    "agrifusion weighted": "fig_agrifusion.png",
    "yield risk distribution": "fig_dataset_distribution.png",
    "per-crop sample counts": "fig_dataset_distribution.png",
}

EQUATION_PATTERNS = [
    r"p_fused",
    r"p_rf",
    r"p_xgb",
    r"w_rf",
    r"w_xgb",
    r"yield_score",
    r"Nernst",
    r"σ",
    r"μ",
]


def _insert_paragraph_after(paragraph: Paragraph, text: str, style: str = "Normal") -> Paragraph:
    new_p = copy.deepcopy(paragraph._element)
    paragraph._element.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    new_para.style = style
    new_para.text = text
    return new_para


def _remove_paragraph(paragraph: Paragraph) -> None:
    p = paragraph._element
    p.getparent().remove(p)


def _sort_citations_in_text(text: str) -> str:
    def sort_cluster(match: re.Match) -> str:
        nums = sorted({int(x) for x in re.findall(r"\d+", match.group(0))})
        return ", ".join(f"[{n}]" for n in nums)

    prev = None
    while prev != text:
        prev = text
        text = re.sub(r"(?:\[\d+\]\s*,\s*)+\[\d+\]", sort_cluster, text)
    return text


def _sort_scattered_citation_clusters(text: str) -> str:
    """Sort consecutive bracket citations even when only whitespace separates them."""
    tokens = re.split(r"(\[\d+\])", text)
    i = 0
    while i < len(tokens):
        if not tokens[i].startswith("["):
            i += 1
            continue
        cluster = [tokens[i]]
        j = i + 1
        while j < len(tokens):
            between = tokens[j]
            if between.strip() in ("", ","):
                if j + 1 < len(tokens) and tokens[j + 1].startswith("["):
                    cluster.append(tokens[j + 1])
                    j += 2
                    continue
            break
        if len(cluster) > 1:
            nums = sorted({int(re.search(r"\d+", c).group()) for c in cluster})
            replacement = ", ".join(f"[{n}]" for n in nums)
            tokens[i : j] = [replacement]
            i += 1
        else:
            i += 1
    return "".join(tokens)


def _remove_duplicate_figure_captions(doc: Document) -> None:
    seen: set[str] = set()
    to_remove: list[Paragraph] = []
    for para in doc.paragraphs:
        m = re.match(r"^Fig\.?\s*(?:\d+|X)\.\s*(.+)", para.text.strip(), re.I)
        if not m:
            continue
        body = re.sub(r"\s+", " ", m.group(1).strip().lower())
        if body in seen:
            prev = para._element.getprevious()
            if prev is not None and prev.tag.endswith("p"):
                to_remove.append(Paragraph(prev, para._parent))
            to_remove.append(para)
        else:
            seen.add(body)
    for para in to_remove:
        _remove_paragraph(para)


def _renumber_figures(doc: Document) -> None:
    """Renumber all figure captions sequentially in document order; update cross-references."""
    captions: list[tuple[Paragraph, int | None, str]] = []
    for para in doc.paragraphs:
        m = re.match(r"^Fig\.?\s*(\d+|X)\.\s*(.+)", para.text.strip(), re.I)
        if m:
            old = None if m.group(1).upper() == "X" else int(m.group(1))
            captions.append((para, old, m.group(2).strip()))

    old_to_new: dict[int, int] = {}
    for new_num, (_, old_num, title) in enumerate(captions, start=1):
        para = captions[new_num - 1][0]
        para.text = f"Fig. {new_num}. {title}"
        if old_num is not None:
            old_to_new[old_num] = new_num

    # Update cross-references (highest old number first to avoid collisions)
    for old in sorted(old_to_new, reverse=True):
        new = old_to_new[old]
        for para in doc.paragraphs:
            if re.match(r"^Fig\.?\s*(\d+|X)\.", para.text.strip(), re.I):
                continue
            para.text = re.sub(
                rf"\bFig\.?\s*{old}\b",
                f"Fig. {new}",
                para.text,
                flags=re.I,
            )


def _italicize_equation_paragraph(paragraph: Paragraph) -> None:
    text = paragraph.text
    if not text.strip():
        return
    is_equation = bool(
        re.search(r"\.\.\.\s*\(\d+\)", text)
        or re.match(r"^\s*p_fused\s*=", text)
        or re.match(r"^\s*ALGORITHM:", text, re.I)
    )
    if not is_equation and not any(
        k in text for k in ["p_fused", "w_rf", "w_xgb", "yield_score"]
    ):
        return
    vars_re = re.compile(
        r"\b(p_fused|p_rf|p_xgb|w_rf|w_xgb|yield_score|damp|floor|σ|μ)\b"
    )
    if not vars_re.search(text):
        return
    original = text
    paragraph.clear()
    last = 0
    for m in vars_re.finditer(original):
        if m.start() > last:
            paragraph.add_run(original[last : m.start()])
        run = paragraph.add_run(m.group(0))
        run.italic = True
        last = m.end()
    if last < len(original):
        paragraph.add_run(original[last:])


def _renumber_tables(doc: Document) -> None:
    """Renumber uppercase TABLE captions only (IEEE style), leave narrative 'Table N ...' text alone."""
    table_idx = 0
    for para in doc.paragraphs:
        t = para.text.strip()
        if not re.match(r"^TABLE\s+[IVXLC\d]", t):  # case-sensitive: uppercase TABLE only
            continue
        if len(t) > 160:
            continue
        table_idx += 1
        rest = re.sub(r"^TABLE\s+[IVXLC\d\-A-Z\.]+\.\s*", "", t)
        para.text = f"TABLE {table_idx}. {rest}"
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER


def _ensure_table_captions(doc: Document) -> None:
    """Promote narrative 'Table N ...' lines immediately above tables into TABLE captions."""
    body = doc.element.body
    for tbl in body.iter(qn("w:tbl")):
        prev = tbl.getprevious()
        if prev is None or not prev.tag.endswith("p"):
            continue
        text = "".join(prev.itertext()).strip()
        if re.match(r"^TABLE\s+", text):
            continue
        m = re.match(
            r"^Table\s+([IVXLC\d\-A-Z\.]+)\s+(.+)$",
            text,
            re.I,
        )
        if m and len(text) < 200:
            label = m.group(1).upper()
            desc = m.group(2).strip().rstrip(".")
            if desc.lower().startswith(("summarizes", "catalogs", "reports", "lists")):
                short = desc.split(".")[0]
                prev_p = Paragraph(prev, doc.paragraphs[0]._parent)
                prev_p.text = f"TABLE {label}. {short.capitalize()}"
                prev_p.alignment = WD_ALIGN_PARAGRAPH.CENTER


def _scale_images(doc: Document, min_width_in: float = 6.0) -> None:
    for para in doc.paragraphs:
        for run in para.runs:
            for ext in run._element.findall(".//" + qn("wp:extent")):
                cx = int(ext.get("cx", 0))
                cy = int(ext.get("cy", 0))
                if cx <= 0:
                    continue
                width_in = cx / 914400
                if width_in < min_width_in:
                    scale = min_width_in / width_in
                    ext.set("cx", str(int(cx * scale)))
                    ext.set("cy", str(int(cy * scale)))


def _replace_figure_image(paragraph: Paragraph, image_path: Path, width_in: float = 6.2) -> None:
    if not image_path.exists():
        return
    # Clear runs with images, keep caption text
    caption = paragraph.text
    for run in list(paragraph.runs):
        run._element.getparent().remove(run._element)
    # Image in previous paragraph typically; find image in prev sibling
    prev = paragraph._element.getprevious()
    if prev is not None:
        for blip in prev.iter(qn("a:blip")):
            blip.getparent().getparent().getparent().getparent().getparent().getparent().remove(
                blip.getparent().getparent().getparent().getparent().getparent()
            )
    # Insert image paragraph before caption
    img_para = paragraph.insert_paragraph_before()
    img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = img_para.add_run()
    run.add_picture(str(image_path), width=Inches(width_in))
    paragraph.text = caption


def _insert_methodology_figure(doc: Document) -> None:
    """Insert methodology flowchart at start of Section III (heading only)."""
    fig_path = FIG_DIR / "fig_methodology_flowchart.png"
    if not fig_path.exists():
        return
    for i, para in enumerate(doc.paragraphs):
        t = para.text.strip()
        if not re.match(r"^III\.\s+", t):
            continue
        for j in range(1, 6):
            idx = i + j
            if idx >= len(doc.paragraphs):
                break
            if "methodology flowchart" in doc.paragraphs[idx].text.lower():
                return
        anchor = doc.paragraphs[i + 1] if i + 1 < len(doc.paragraphs) else para
        img_para = _insert_paragraph_after(anchor, "")
        img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        img_para.add_run().add_picture(str(fig_path), width=Inches(6.2))
        cap = _insert_paragraph_after(
            img_para, "Fig. X. AgriXplain system design methodology flowchart."
        )
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        return


def _replace_regenerated_figures(doc: Document) -> None:
    for para in doc.paragraphs:
        cap = para.text.lower()
        if not cap.startswith("fig"):
            continue
        for keyword, fname in FIGURE_REPLACEMENTS.items():
            if keyword in cap:
                path = FIG_DIR / fname
                if path.exists():
                    prev = para._element.getprevious()
                    if prev is not None and prev.tag.endswith("p"):
                        prev_para = Paragraph(prev, para._parent)
                        # Remove old image runs from previous paragraph
                        for run in list(prev_para.runs):
                            if run._element.findall(".//" + qn("a:blip")):
                                run._element.getparent().remove(run._element)
                        if not prev_para._element.findall(".//" + qn("a:blip")):
                            prev_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                            prev_para.add_run().add_picture(str(path), width=Inches(6.2))
                break


def _fix_introduction(doc: Document) -> None:
    """Remove duplicate subsections; add Research Gaps and Research Questions."""
    if any(p.text.strip().startswith("C. Research Gaps") for p in doc.paragraphs):
        # Still clean duplicate blocks if present
        pass
    else:
        anchor = None
        for para in doc.paragraphs:
            t = para.text.strip()
            if t.startswith("B. Paper Organization"):
                anchor = para
                break
            if t.startswith("The rest of this paper is organized"):
                anchor = para
                break
        if anchor is not None:
            gaps_para = _insert_paragraph_after(anchor, RESEARCH_GAPS)
            _insert_paragraph_after(gaps_para, RESEARCH_QUESTIONS)

    # Remove duplicate Paper Organization / contributions blocks
    seen: set[str] = set()
    to_remove: list[Paragraph] = []
    for para in doc.paragraphs:
        t = para.text.strip()
        key = None
        if t.startswith("B. Paper Organization"):
            key = "org"
        elif t.startswith("A. Research Contributions"):
            key = "contrib"
        elif t.startswith("The specific contributions of this work"):
            key = "contrib_body"
        elif t.startswith("Section II provides an extended review"):
            key = "org_body"
        if key:
            if key in seen:
                to_remove.append(para)
            else:
                seen.add(key)
    for para in to_remove:
        _remove_paragraph(para)

    # Add dataset intro once
    if not any(p.text.strip().startswith("E. Benchmark Dataset Summary") for p in doc.paragraphs):
        for para in doc.paragraphs:
            if para.text.strip().startswith("D. Research Questions"):
                _insert_paragraph_after(para, DATASET_INTRO)
                break


def _add_dataset_content(doc: Document) -> None:
    """Expand ML dataset subsection with figure and notes."""
    for i, para in enumerate(doc.paragraphs):
        if "Synthetic Dataset" in para.text or "Synthetic Training Dataset" in para.text:
            nxt_idx = i + 1
            if nxt_idx < len(doc.paragraphs) and "training_data.csv" in doc.paragraphs[nxt_idx].text:
                return
            nxt = doc.paragraphs[nxt_idx] if nxt_idx < len(doc.paragraphs) else para
            _insert_paragraph_after(nxt, DATASET_ML_EXPAND)
            fig_path = FIG_DIR / "fig_dataset_distribution.png"
            if fig_path.exists():
                img_p = _insert_paragraph_after(nxt, "")
                img_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                img_p.add_run().add_picture(str(fig_path), width=Inches(6.2))
                cap = _insert_paragraph_after(
                    img_p,
                    "Fig. X. Synthetic benchmark dataset: per-crop sample counts and yield-class distribution.",
                )
                cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
            break


def _fix_references_borders(doc: Document) -> None:
    """Ensure references use [n] bracket format consistently."""
    in_refs = False
    for para in doc.paragraphs:
        t = para.text.strip()
        if t == "References":
            in_refs = True
            continue
        if in_refs and t:
            if not t.startswith("["):
                m = re.match(r"^(\d+)\.?\s+(.*)", t)
                if m:
                    para.text = f"[{m.group(1)}] {m.group(2)}"


def fix_document(src: Path, dst: Path) -> None:
    print(f"Processing {src.name}...")
    doc = Document(str(src))

    _fix_introduction(doc)
    _add_dataset_content(doc)
    _insert_methodology_figure(doc)
    _replace_regenerated_figures(doc)

    for para in doc.paragraphs:
        para.text = _sort_scattered_citation_clusters(_sort_citations_in_text(para.text))

    _remove_duplicate_figure_captions(doc)
    _renumber_figures(doc)
    _renumber_tables(doc)
    _ensure_table_captions(doc)
    _fix_references_borders(doc)
    _scale_images(doc, min_width_in=6.0)

    for para in doc.paragraphs:
        _italicize_equation_paragraph(para)

    doc.save(str(dst))
    print(f"  Saved -> {dst.name}")


def main() -> None:
    jobs = [
        (
            PAPER_DIR / "AgriXplain_Journal_v3_Updated.docx",
            PAPER_DIR / "AgriXplain_Journal_v3_SirReview.docx",
        ),
        (
            PAPER_DIR / "AgriXplain_Conference_v3.docx",
            PAPER_DIR / "AgriXplain_Conference_v3_SirReview.docx",
        ),
    ]
    for src, dst in jobs:
        if not src.exists():
            print(f"SKIP missing: {src}")
            continue
        fix_document(src, dst)


if __name__ == "__main__":
    main()
